version: '2'

services:
  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - 4401:3307
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dzavapelikany"

  wildfly:
    build:
      context: ./dzavapelikanyWebApp
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 4400:8080
      - 4402:9990
    environment:
      - TZ=Europe/Warsaw
